name: grizzly_prng
description: Pseudo Random Number Generator.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  ninja: ^3.0.8
  ninja_hex: ^2.0.1
  ninja_prime:

dependency_overrides:
  ninja_prime:
    path: ../prime

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7
